print ("Hell0 W0rld!")
require("options")
require("keymaps")
require("plugins.plugins")
require("plugins.theme")
require("plugins.treesitter")
require("plugins.nvim-tree")
require("plugins.lualine")
-- LSP
require("lsp.mason")
require("lsp.cmp")
